/*
 * Copyright © 2025-2026 Callibrity, Inc. (contactus@callibrity.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.callibrity.mocapi.examples.apps;

import static org.assertj.core.api.Assertions.assertThat;

import com.callibrity.mocapi.model.Tool;
import com.callibrity.mocapi.server.resources.McpResourcesService;
import com.callibrity.mocapi.server.tools.McpToolsService;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Boots the real application context to prove the leanest wiring works: {@link GetTimeApp} is a
 * plain {@code @Component}, component-scanned and discovered by mocapi's handler scan — no
 * example-specific auto-configuration. Also confirms {@code @McpUi(resource=…)} serve-mode
 * registered the {@code ui://} resource (its bundle is generated by the frontend build).
 */
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@SpringBootTest
class AppsExampleContextTest {

  @Autowired private McpToolsService tools;
  @Autowired private McpResourcesService resources;

  @Test
  void get_time_tool_is_discovered_via_component_scan() {
    assertThat(tools.listTools(null).tools()).extracting(Tool::name).contains("get-time");
  }

  @Test
  void serve_mode_registered_the_ui_resource() {
    assertThat(resources.resourceUris()).contains("ui://get-time/mcp-app.html");
  }
}
