mocapi.server-name=${spring.application.name:mocapi}
mocapi.server-title=Callibrity Mocapi MCP Server
mocapi.server-version=unknown
mocapi.session-timeout=PT1H
mocapi.allowed-origins=localhost,127.0.0.1,[::1]
mocapi.elicitation.timeout=PT5M
mocapi.sampling.timeout=PT30S
mocapi.pagination.page-size=50
mocapi.endpoint=/mcp
